name: Health Check Run

on:
  deployment_status: null


jobs:
  ui-trello-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker
        run: |
          docker compose build
      - name: Run docker compose
        run: |
          docker compose up
