name: Selenium Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome
      run: |
        sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
        sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get -y update
        sudo apt-get -y install google-chrome-stable

    - name: Install ChromeDriver
      run: |
        CHROME_IN_PATH=$(which google-chrome)
        CHROME_BIN_DIR=$(dirname $CHROME_IN_PATH)
        CHROME_VER=$($CHROME_IN_PATH --product-version)
        CHROME_DRIVER_VER=$(curl --location --request GET 'https://chromedriver.storage.googleapis.com/LATEST_RELEASE_'$CHROME_VER)
        curl "https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VER}/chromedriver_linux64.zip" -O
        unzip chromedriver_linux64.zip -d $CHROME_BIN_DIR
        rm chromedriver_linux64.zip
        sudo chmod +x $CHROME_BIN_DIR/chromedriver

    - name: Run tests
      run: |
        pytest -m TC001